# [START cloudbuild]
steps:
# This step runs the unit tests on the app
- name: 'node'
  id: Test
  entrypoint: npm
  args:
  - 'cd web && npm install && npm run test:ci'

# This step builds the container image.
- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args:
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/web:$SHORT_SHA'
  - '-f'
  - 'web/Dockerfile'
  - '.'

# This step pushes the image to Container Registry
# The PROJECT_ID and SHORT_SHA variables are automatically
# replaced by Cloud Build.
- name: 'gcr.io/cloud-builders/docker'
  id: Push
  args:
  - 'push'
  - 'gcr.io/$PROJECT_ID/web:$SHORT_SHA'
# [END cloudbuild]